#if !canImport(ObjectiveC)
import XCTest

extension GildedRoseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GildedRoseTests = [
        ("testTheTruth", testTheTruth),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GildedRoseTests.__allTests__GildedRoseTests),
    ]
}
#endif
